config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :cats 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint           not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Cat < ApplicationRecord
  include ActionView::Helpers::DateHelper
  COLORS = ['black', 'blue', 'red', 'green', 'white', 'orange', 'brown', 'gray']
  validates :color, inclusion: COLORS, presence: true
  
  SEX = ['M', 'F']
  validates :sex, inclusion: SEX, presence: true
  
  TODAY = Date::today(Date::ITALY)

  def age
    days = (TODAY - birth_date).to_i + 1
    days / 365
  end

  has_many :rental_requests,
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: :CatRentalRequest


end

app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :bigint           not null, primary key
#  cat_id     :integer          not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string           not null
#

class CatRentalRequest < ApplicationRecord
  validates :status, inclusion: ['PENDING', 'APPROVED', 'DENIED'], presence: true
  validates :cat_id, presence: true
  dependent: :destroy

  belongs_to :cat,
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: :Cat

  def overlapping_requests
    
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all
    render :index
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render json: cat.errors.full_messages, status: 422
    end
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    cat = Cat.new(cat_params)
    if cat.save
      redirect_to cat_url(cat)
    else
      render json: cat.errors.full_messages, status: 422
    end
  end

  

  private

  def cat_params
      params.require(:cat).permit(:name, :birth_date, :color, :sex, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cats/_form.html.erb
<% if edit %>
  <% action = cat_url %>
  <% button_text = 'Update cat'%>
  <% title = 'edit cat' %>
<% else %>
  <% action = cats_url %>
  <% button_text = 'New cat' %>
  <% title = 'new cat' %>
<% end%>


<h1> <%= title %> </h1>
<form action="<%= action %>" method="POST">
  <% if edit %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>
  <label for="name">Name</label>
  <% if edit %>
    <input type= "input" name = "cat[name]" id="name" value="<%= @cat.name %>">
    <label for="date">Birth date</label>
    <input type= "date" name = "cat[birth_date]" id="date" value="<%= @cat.birth_date %>">
  <% else %>
    <input type= "input" name = "cat[name]" id="name">
    <label for="date">Birth date</label>
    <input type= "date" name = "cat[birth_date]" id="date">
  <% end %>

  <label for="color">Color</label>

    <select name = "cat[color]">
      <% if edit %>
        <option selected value="<%= @cat.color %>"><%= @cat.color %></option>
      <% end %>
      <option value="black">black</option>
      <option value="green">green</option>
      <option value="orange">orange</option>
      <option value="blue">blue</option>
      <option value="white">white</option>
      <option value="gray">gray</option>
      <option value="brown">brown</option>
      <option value="red">red</option>
  </select>
  <% if edit %>
    <% if @cat.sex == "M" %>
      <input type="radio" id="m" name="cat[sex]" value="M" checked>
      <label for="m">M</label>
      <input type="radio" id="f" name="cat[sex]" value="F">
      <label for="f">F</label>
    <% else %>
      <input type="radio" id="m" name="cat[sex]" value="M">
      <label for="m">M</label>
      <input type="radio" id="f" name="cat[sex]" value="F" checked>
      <label for="f">F</label>
    <% end %>
  <% else %>
    <input type="radio" id="m" name="cat[sex]" value="M" checked>
    <label for="m">M</label>
    <input type="radio" id="f" name="cat[sex]" value="F">
    <label for="f">F</label>
  <% end %>

  <br><br><br>
  <label for="description">Description</label>
  <br>
  <% if edit %>
    <textarea id="description" name="cat[description]" rows="8" cols="80"><%= @cat.description %></textarea>
  <% else %>
    <textarea id="description" name="cat[description]" rows="8" cols="80"></textarea>
  <% end %>
  <br>
  <label for="submit">Submit</label>
  <input type= "submit" name = "submit" id="submit" value = "<%= button_text %>">

app/views/cats/edit.html.erb
<%= render 'form', edit: true, cat: @cat %>

<!--
# <h1>EDIT CAT</h1>
# <form action="<%= cat_url %>" method="POST">
#   <input type="hidden" name="_method" value="PATCH">
#   <label for="name">Name</label>
#   <input type= "input" name = "cat[name]" id="name" value="<%= @cat.name %>">
#   <label for="date">Birth date</label>
#   <input type= "date" name = "cat[birth_date]" id="date" value="<%= @cat.birth_date %>">
#   <label for="color">Color</label>
#   <select name = "cat[color]">
#     <option selected value="<%= @cat.color %>"><%= @cat.color %></option>
#     <option value="black">black</option>
#     <option value="green">green</option>
#     <option value="orange">orange</option>
#     <option value="blue">blue</option>
#     <option value="white">white</option>
#     <option value="gray">gray</option>
#     <option value="brown">brown</option>
#     <option value="red">red</option>
#   </select>
#   <% if @cat.sex == "M" %>
#     <input type="radio" id="m" name="cat[sex]" value="M" checked>
#     <label for="m">M</label>
#     <input type="radio" id="f" name="cat[sex]" value="F">
#     <label for="f">F</label>
#   <% else %>
#     <input type="radio" id="m" name="cat[sex]" value="M">
#     <label for="m">M</label>
#     <input type="radio" id="f" name="cat[sex]" value="F" checked>
#     <label for="f">F</label>
#   <% end %>
#   <br><br><br>
#   <label for="description">Description</label>
#   <br>
#   <textarea id="description" name="cat[description]" rows="8" cols="80"><%= @cat.description %></textarea>
#   <br>
#   <label for="submit">Submit</label>
#   <input type= "submit" name = "Submit" id="submit">
# </form> --->

app/views/cats/index.html.erb
<h1>CATS</h1>

<ul>
  <% @cats.each do |cat| %>
    <li>
      <%= cat.name %>
      <a href="<%= cat_url(cat) %>">Show</a>
    </li>
  <% end %>
</ul>

app/views/cats/new.html.erb
<%= render 'form', edit: false, cat: @cat %>

<!--
# <h1>CREATE NEW CAT</h1>
# <form action="<%= cats_url %>" method="POST"> 
#   <label for="name">Name</label>
#   <input type= "input" name = "cat[name]" id="name">
#   <label for="date">Birth date</label>
#   <input type= "date" name = "cat[birth_date]" id="date">
#   <label for="color">Color</label>
#   <select name = "cat[color]">
#     <option disabled>Please select a color...</option>
#     <option value="black">black</option>
#     <option value="green">green</option>
#     <option value="orange">orange</option>
#     <option value="blue">blue</option>
#     <option value="white">white</option>
#     <option value="gray">gray</option>
#     <option value="brown">brown</option>
#     <option value="red">red</option>
#   </select>
#   <input type="radio" id="m" name="cat[sex]" value="M">
#   <label for="m">M</label>
#   <input type="radio" id="f" name="cat[sex]" value="F">
#   <label for="f">F</label>
#   <br><br><br>
#   <label for="description">Description</label>
#   <br>
#   <textarea id="description" name="cat[description]" rows="8" cols="80"></textarea>
#   <br>
#   <label for="submit">Submit</label>
#   <input type= "submit" name = "Submit" id="submit">
# </form> -->

app/views/cats/show.html.erb
<table style= "border: 1px solid #333">
  <thead>
    <tr>
      <th colspan="2"<h1><%= @cat.name %></h1></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style= "border: 1px solid #333"> <h2>Color:</h2> </td>
      <td style= "border: 1px solid #333"><h2 style="color: <%= @cat.color %>"><%= @cat.color %></h2></td>
    </tr>
    <tr>
      <td style= "border: 1px solid #333"> <h2>Age:</h2> </td>
      <td style= "border: 1px solid #333"><h2><%= @cat.age %></h2></td>
    </tr>
    <tr>
      <td style= "border: 1px solid #333"> <h2>Sex:</h2> </td>
      <td style= "border: 1px solid #333"><h2><%= @cat.sex %></h2></td>
    </tr>
    </tr>
    <tr>
      <td style= "border: 1px solid #333"> <h2>Description:</h2> </td>
      <td style= "border: 1px solid #333"><h2><%= @cat.description %></h2></td>
    </tr>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- <%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>-->
  </head>

  <body bgcolor="cyan" style="font-family: Comic Sans MS;font-size:18pt">
    <%= yield %>
  </body>
</html>